name: Update Sources

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        
      - name: Install dependencies
        run: |
          sudo apt install jq git curl rsync xz-utils unzip zip libxml2 libc++abi-dev
          git config --global user.name "AltStore Sources"
          git config --global user.email actions@github.com
          git clone https://github.com/Al4ise/Azule ${{ github.workspace }}/Azule
          ln -sf ${{ github.workspace }}/Azule/azule ${{ github.workspace }}/uYouPlus/azule
          cd EnmityCustomIcons
          npm i
    
      - name: Update Enmity Custom Icons
        run: |
          cd EnmityCustomIcons
          node enmityCustomIcons.js

      - name: Update uYouPlus
        run: |
          cd uYouPlus
          bash run.sh
          
      - name: Commit changes
        run: |
          git add .
          git diff-index --quiet HEAD || (git commit -m "Update sources" && git push)
